swagger: "2.0"

info:
  version: 0.0.1
  title:  service platform
  description: the first edtion API for service platform
  
schemes: 
  - https
host: www.muxier.top
basePath: /api

tags:
- name: "auth"
  description: 验证权限
- name: "main"
  description: 主界面
- name: "admin"
  description: 管理界面
- name: "user"
  description: 报修界面

paths:

  /signup/:
    post:
      tags:
      - "auth"
      summary: 用户注册
      description: 暂定用户自己注册账号。
      parameters:
      - name: 用户注册信息
        in: body
        required: true
        schema:
          required:
            - username
            - password
            - realname
            - email
          properties:
            username:
              type: string
            password:
              type: string
            realname:
              type: string
            email:
              type: string
      responses:
        201:
          description: 成功创建用户
          schema:
            required:
              - token
            properties:
              token:
                description: 用户登陆密钥
                type: string
        500:
          description: 服务器端错误

  /signin/:
    post:
      tags:
      - "auth"
      summary: 验证登陆
      description: 用户登陆，返回token
      parameters:
      - name: 用户登陆信息
        in: body
        schema:
          required:
            - username
            - password
          properties:
            username:
              type: string
            password:
              type: string
      responses:
        200:
          description: 登陆成功
          schema:
            required: 
              - token
            properties:
              token: 
                type: string
        401:
          description: 用户名或密码错误
        500:
          description: 服务器端错误

  /resetpass/:
    get:
      tags:
      - "auth"
      summary: 获得验证码
      description: 通过邮箱验证获得修改密码的验证码
      parameters:
      - name: 重设密码
        in: body
        schema:
          required:
            - username
            - email
          properties:
            username:
              type: string
            email:
              type: string
      responses:
        200:
          description: 邮件成功发送
        401:
          description: 邮箱错误
        500: 
          description: 服务器端错误
    post:
      tags:
      - "auth"
      summary: 修改密码
      description: 提交验证码并修改密码
      parameters:
      - name: 重设密码
        in: body
        schema:
          required:
            - username
            - email
            - security_code
          properties:
            username: 
              type: string
            email:
              type: string
            security_code:
              type: string
      responses:
        200:
          description: 成功修改密码
        401:
          description: 验证码错误
        500:
          description: 服务器端错误

  /admin/pages/{pageNumber}/:
    get:
      tags: 
      - "admin"
      summary: 管理界面
      description: 显示待操作的消息,每次返回十五条消息
      parameters: 
        - in: header
          name: token
          description: 表识管理员身份
          required: true
          type: string
        - in: path
          name: pageNumber
          description: 需要显示第几页
          required: true
          type: integer
      responses:
        200:
          description: 返回待发送的消息
          schema:
            type: array
            items:
              required: 
                - id
                - sent_content
                - sent_name
                - sent_time
                - sent_address
                - sent_status
              properties:
                id:
                  type: integer
                sent_content:
                  type: string
                sent_name:
                  type: string
                sent_time:
                  type: string
                sent_address:
                  type: string
                sent_status:
                  type: string
        403:
          description: Forbidden
          
  /admin/pages/{pageNumber}/time/{time}/:
    get:
      tags: 
      - "admin"
      summary: 管理界面
      description: 按时间选择显示待操作的消息，每次返回十五条消息
      parameters: 
        - in: header
          name: token
          description: 表识管理员身份
          required: true
          type: string
        - in: path
          name: pageNumber
          description: 需要显示第几页
          required: true
          type: integer
        - in: path
          name: time
          description: 发送的时间
          required: true
          type: string
      responses:
        200:
          description: 返回待发送的消息
          schema:
            type: array
            items:
              required: 
                - id
                - sent_content
                - sent_name
                - sent_time
                - sent_address
                - sent_status
              properties:
                id:
                  type: integer
                sent_content:
                  type: string
                sent_name:
                  type: string
                sent_time:
                  type: string
                sent_address:
                  type: string
                sent_status:
                  type: string
        403:
          description: Forbidden


  /sent/{message_id}/:
    post:
      tags:
      - "admin"
      summary: 单条发送信息或邮件
      description: 批量发送由前端实现，即批量发送返回多次请求。
      parameters: 
      - in: header
        name: token
        description: 标识管理员身份
        required: true
        type: string
      - in: path
        name: message_id
        description: 所要发送的消息的ID
        required: true
        type: integer
      responses:
        200:
          description: OK
        403:
          description: Forbidden
        500:
          description: server error
        

definitions:
  Message:
    required: 
      - id
      - title
      - time
      - status
      - building
      - goods
      - email
      - house_number
      - content
      - evaluate
    properties:
      id:
        description: 消息ID
        type: integer
      title:
        description: 消息标题
        type: string
      time:
        description: 报修时间
        type: string
      status:
        description: 1.未处理    2.已处理
        type: integer
      building:
        description: 楼栋名（例：东十六）
        type: string
      goods:
        description: 维修物品
        type: string
      email:
        description: 联系方式
        type: string
      house_number:
        description: 门牌号
        type: string
      content:
        description: 具体问题描述
        type: string
      evaluate:
        description: 维修任务评价（任务发起人可以评价）
        type: string
  User:
    required:
      - id
      - username
      - realname
      - email
      - password
      - role
    properties:
      id:
        description: 用户ID
        type: integer
      username:
        description: 账号名
        type: integer
      realname:
        description: 用户真实姓名
        type: string
      email:
        description: 用户联系方式
        type: string
      role:
        description: 用户角色:1.普通用户 2.维修工 3.管理员 4.超级用户（对应登陆页面不显示给用户，我们通过相应API进入）
        type: integer